### ISSUE TITLE
add flag --servName to loxicmd delete

### ISSUE THREAD

**Issue by vincentmli** [loxilb-io/loxicmd#24]
loxicmd get lb has `--servName` flag to query specific lb with lb name,  add same `--servName` to loxicmd delete lb would make it easier for user to delete specific lb with lb name.

**Comment by UltraInstinct14** [comment]
The feature has been added. To add rule with name (already existing feature) -
```
loxicmd create lb 10.10.10.254 --sctp=2020:8080 --endpoints=31.31.31.1:1,32.32.32.1:1  --name=sctp-r1
```

To delete rule with name - 
```
loxicmd delete lb --name=sctp-r1
```
